version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: binance-oto-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: binance_oto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: binance-oto-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 可选：API服务容器（用于生产部署）
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance-oto-api
    depends_on:
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/binance.db
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    command: uvicorn binance.api.main:app --host 0.0.0.0 --port 8000
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:

