# 统一交易配置文件

# ============================================================================
# 全局设置
# ============================================================================
global_settings:
  # 交易参数（刷量策略：高买低卖）
  default_buy_offset_percentage: 10           # 默认买入溢价 %（高于市价）
  default_sell_profit_percentage: 10          # 默认卖出折扣 %（低于市价）
  default_trade_interval_seconds: 1            # 默认交易间隔 1 秒
  default_single_trade_amount_usdt: 200         # 默认单次交易金额 30 USDT
  default_volume_check_delay_seconds: 120       # 默认批次完成后等待时间（秒），让交易量数据更新
  
  # 风控参数
  max_concurrent_users: 10                     # 最大并发用户数
  max_price_volatility_percentage: 5.0         # 最大价格波动 5%
  max_retry_attempts: 3                        # 最大重试次数
  retry_delay_seconds: 5                       # 重试延迟（秒）
  order_timeout_seconds: 300                   # 订单超时时间 5 分钟


# ============================================================================
# 策略配置
# ============================================================================
strategies:
  # KOGE 刷量策略
  - strategy_id: "high"
    strategy_name: "高量池"
    enabled: true                              # 所有用户已达标，暂时禁用
    target_token: MERL
    target_chain: BSC
    target_volume: 8200                       
    volume_check_delay_seconds: 60              
    single_trade_amount_usdt: 200               
    trade_interval_seconds: 1  
    user_ids: [3,4,5,6,7]                              # 参与用户
    # 其他参数使用全局默认值

  # AOP 测试策略
  - strategy_id: "low"
    strategy_name: "低量池"
    enabled: true                              # 所有用户已达标，暂时禁用
    target_token: CDL
    target_chain: BSC
    target_volume: 4096                         # 目标：今日总交易量达到 18000 USDT（真实值）
    volume_check_delay_seconds: 60               # 批次完成后等待5秒（测试用）
    single_trade_amount_usdt: 200               # 单笔交易额 200 USDT
    trade_interval_seconds: 1                  # 交易间隔 1 秒
    user_ids: [1,2]                             # 参与用户


