"""
API常量

API相关的常量定义。
"""


class ApiConstants:
    """API常量"""
    
    # 基础URL
    BASE_URL_BINANCE = "https://www.binance.com"
    BASE_URL_BINANCE_TESTNET = "https://testnet.binance.com"
    
    # WebSocket URL
    WS_URL_PUBLIC = "wss://nbstream.binance.com/w3w/wsa/stream"
    WS_URL_PRIVATE = "wss://nbstream.binance.com/w3w/stream"
    
    # API版本
    API_VERSION_V1 = "v1"
    API_VERSION_V2 = "v2"
    
    # 请求方法
    HTTP_METHOD_GET = "GET"
    HTTP_METHOD_POST = "POST"
    HTTP_METHOD_PUT = "PUT"
    HTTP_METHOD_DELETE = "DELETE"
    
    # 内容类型
    CONTENT_TYPE_JSON = "application/json"
    CONTENT_TYPE_FORM = "application/x-www-form-urlencoded"
    CONTENT_TYPE_MULTIPART = "multipart/form-data"
    
    # 请求头
    HEADER_AUTHORIZATION = "Authorization"
    HEADER_CONTENT_TYPE = "Content-Type"
    HEADER_USER_AGENT = "User-Agent"
    HEADER_ACCEPT = "Accept"
    HEADER_ACCEPT_LANGUAGE = "Accept-Language"
    HEADER_ACCEPT_ENCODING = "Accept-Encoding"
    HEADER_ORIGIN = "Origin"
    HEADER_REFERER = "Referer"
    HEADER_SEC_FETCH_DEST = "Sec-Fetch-Dest"
    HEADER_SEC_FETCH_MODE = "Sec-Fetch-Mode"
    HEADER_SEC_FETCH_SITE = "Sec-Fetch-Site"
    HEADER_X_REQUESTED_WITH = "X-Requested-With"
    HEADER_X_API_KEY = "X-API-Key"
    HEADER_X_SIGNATURE = "X-Signature"
    HEADER_X_TIMESTAMP = "X-Timestamp"
    HEADER_X_RECV_WINDOW = "X-Recv-Window"
    
    # 响应状态码
    HTTP_STATUS_OK = 200
    HTTP_STATUS_CREATED = 201
    HTTP_STATUS_ACCEPTED = 202
    HTTP_STATUS_NO_CONTENT = 204
    HTTP_STATUS_BAD_REQUEST = 400
    HTTP_STATUS_UNAUTHORIZED = 401
    HTTP_STATUS_FORBIDDEN = 403
    HTTP_STATUS_NOT_FOUND = 404
    HTTP_STATUS_METHOD_NOT_ALLOWED = 405
    HTTP_STATUS_TOO_MANY_REQUESTS = 429
    HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
    HTTP_STATUS_BAD_GATEWAY = 502
    HTTP_STATUS_SERVICE_UNAVAILABLE = 503
    HTTP_STATUS_GATEWAY_TIMEOUT = 504
    
    # 错误代码
    ERROR_CODE_SUCCESS = "000000"
    ERROR_CODE_INVALID_REQUEST = "400001"
    ERROR_CODE_INVALID_SYMBOL = "400002"
    ERROR_CODE_INVALID_QUANTITY = "400003"
    ERROR_CODE_INVALID_PRICE = "400004"
    ERROR_CODE_INSUFFICIENT_BALANCE = "400005"
    ERROR_CODE_ORDER_NOT_FOUND = "400006"
    ERROR_CODE_ORDER_ALREADY_EXISTS = "400007"
    ERROR_CODE_ORDER_CANNOT_BE_CANCELED = "400008"
    ERROR_CODE_RATE_LIMIT_EXCEEDED = "429001"
    ERROR_CODE_INTERNAL_SERVER_ERROR = "500001"
    
    # 速率限制
    RATE_LIMIT_REQUESTS_PER_MINUTE = 1200
    RATE_LIMIT_REQUESTS_PER_SECOND = 20
    RATE_LIMIT_WEIGHT_PER_MINUTE = 6000
    RATE_LIMIT_WEIGHT_PER_SECOND = 100
    
    # 超时配置
    DEFAULT_TIMEOUT = 30
    DEFAULT_CONNECT_TIMEOUT = 10
    DEFAULT_READ_TIMEOUT = 30
    DEFAULT_WRITE_TIMEOUT = 30
    
    # 重试配置
    DEFAULT_RETRY_COUNT = 3
    DEFAULT_RETRY_DELAY = 1.0
    DEFAULT_RETRY_BACKOFF = 2.0
    DEFAULT_RETRY_MAX_DELAY = 60.0
    
    # 连接池配置
    DEFAULT_POOL_SIZE = 100
    DEFAULT_POOL_SIZE_PER_HOST = 30
    DEFAULT_KEEPALIVE_TIMEOUT = 30
    DEFAULT_KEEPALIVE_COUNT = 3
    
    # WebSocket配置
    WS_PING_INTERVAL = 20
    WS_PING_TIMEOUT = 10
    WS_RECONNECT_DELAY = 5
    WS_MAX_RECONNECT_ATTEMPTS = 10
    
    # 流名称
    STREAM_TICKER = "ticker"
    STREAM_TRADE = "aggTrade"
    STREAM_DEPTH = "depth"
    STREAM_KLINE = "kline"
    STREAM_USER_DATA = "userData"
    
    # 订阅方法
    SUBSCRIBE_METHOD = "SUBSCRIBE"
    UNSUBSCRIBE_METHOD = "UNSUBSCRIBE"
    LIST_SUBSCRIPTIONS_METHOD = "LIST_SUBSCRIPTIONS"
    
    # 事件类型
    EVENT_TYPE_ORDER_UPDATE = "executionReport"
    EVENT_TYPE_ACCOUNT_UPDATE = "outboundAccountPosition"
    EVENT_TYPE_BALANCE_UPDATE = "outboundAccountInfo"
    
    # 订单状态
    ORDER_STATUS_NEW = "NEW"
    ORDER_STATUS_PENDING = "PENDING"
    ORDER_STATUS_PARTIALLY_FILLED = "PARTIALLY_FILLED"
    ORDER_STATUS_FILLED = "FILLED"
    ORDER_STATUS_CANCELED = "CANCELED"
    ORDER_STATUS_REJECTED = "REJECTED"
    
    # 订单类型
    ORDER_TYPE_LIMIT = "LIMIT"
    ORDER_TYPE_MARKET = "MARKET"
    ORDER_TYPE_STOP_LOSS = "STOP_LOSS"
    ORDER_TYPE_STOP_LOSS_LIMIT = "STOP_LOSS_LIMIT"
    ORDER_TYPE_TAKE_PROFIT = "TAKE_PROFIT"
    ORDER_TYPE_TAKE_PROFIT_LIMIT = "TAKE_PROFIT_LIMIT"
    ORDER_TYPE_LIMIT_MAKER = "LIMIT_MAKER"
    
    # 订单方向
    ORDER_SIDE_BUY = "BUY"
    ORDER_SIDE_SELL = "SELL"
    
    # 时间有效期
    TIME_IN_FORCE_GTC = "GTC"
    TIME_IN_FORCE_IOC = "IOC"
    TIME_IN_FORCE_FOK = "FOK"
    
    # 用户代理
    DEFAULT_USER_AGENT = "BinanceTools/1.0.0"
    
    # 支持的编码
    SUPPORTED_ENCODINGS = ["gzip", "deflate", "br"]
    
    # 支持的语言
    SUPPORTED_LANGUAGES = ["zh-CN", "en-US", "ja-JP", "ko-KR"]
    
    # 默认语言
    DEFAULT_LANGUAGE = "zh-CN"
    
    # 时区
    DEFAULT_TIMEZONE = "UTC"
    
    # 日期格式
    DATE_FORMAT_ISO = "%Y-%m-%dT%H:%M:%S.%fZ"
    DATE_FORMAT_SIMPLE = "%Y-%m-%d %H:%M:%S"
    
    # 数字格式
    NUMBER_FORMAT_DECIMAL = "decimal"
    NUMBER_FORMAT_STRING = "string"
    
    # 默认数字精度
    DEFAULT_DECIMAL_PRECISION = 8
